server:
  port: 8189
  servlet:
    context-path: /application


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hiber
    username: postgres